spring:
  application:
    name: christmas
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/api-docs
    disable-swagger-default-url: true
    display-request-duration: true

cloud:
  aws:
    s3:
      bucket: test-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  url: ${TEST_SERVER_URL}

map:
  kakao:
    rest-api-key: ${KAKAO_MAP_REST_API_KEY}
    default-url: https://dapi.kakao.com/v2/local
  tmap:
    app-key: ${TMAP_APP_KEY}
    default-url: https://apis.openapi.sk.com/tmap/routes
