name: 🎄Backend Build & Test With Local Profile

on:
  pull_request:
    branches: [ "BE/dev", "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILE: local
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-write-only: true

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: christmas
          mysql root password: 15911591

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            nc -zv 127.0.0.1 3306 && echo "MySQL is ready" && exit 0
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL failed to start in time" && exit 1

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Running Test Code
        run: ./gradlew --stacktrace test
